### ISSUE TITLE
Migrate to ESLint

### ISSUE THREAD

**Issue by bampakoa** [stevermeister/ngx-wig#176]
@stevermeister what do you think about migrating the project to ESLint using the **angular-eslint**?

**Comment by stevermeister** [comment]
@bampakoa yes, sure! good idea! 

the whole migration should be just a few commands:
```
ng add @angular-eslint/schematics
ng g @angular-eslint/schematics:convert-tslint-to-eslint
ng lint
```
and hope that everything works as expected? :)

**Comment by bampakoa** [comment]
Yes, that's correct. Do you want to try it by yourself? 🙂

**Comment by stevermeister** [comment]
after 1 and 2
for `ng lint`
I'm getting a strange error: 
```
[error] Error: Cannot find builder "@angular-devkit/build-angular:tslint".
    at WorkspaceNodeModulesArchitectHost.resolveBuilder (/Users/stevermeister/workspace/stevermeister/ngx-wig/node_modules/@angular-devkit/architect/node/node-modules-architect-host.js:130:19)
    at LintCommandModule.getArchitectTargetOptions (/Users/stevermeister/workspace/stevermeister/ngx-wig/node_modules/@angular/cli/src/command-builder/architect-base-command-module.js:81:47)
    at async LintCommandModule.builder (/Users/stevermeister/workspace/stevermeister/ngx-wig/node_modules/@angular/cli/src/command-builder/architect-command-module.js:50:31)
    at async runCommand (/Users/stevermeister/workspace/stevermeister/ngx-wig/node_modules/@angular/cli/src/command-builder/command-runner.js:111:5)
    at async default_1 (/Users/stevermeister/workspace/stevermeister/ngx-wig/node_modules/@angular/cli/lib/cli/index.js:70:16)
```

**Comment by stevermeister** [comment]
just forgot to specify the project: 
```
ng lint --project=ngx-wig
```

**Comment by stevermeister** [comment]
✖ 45 problems (45 errors, 0 warnings)

and one more command:
```
 ng lint --project=ngx-wig --fix
```

✖ 17 problems (17 errors, 0 warnings)

almost there... :)

**Comment by stevermeister** [comment]
```
All files pass linting.
```

only I have this warning now: 
```
Warning: 'noEslintrc' option has been declared with a 'no' prefix in the schema.Please file an issue with the author of this package.
```

**Comment by stevermeister** [comment]
https://github.com/stevermeister/ngx-wig/pull/178/files
